//
// Created by qwerty on 19.09.16.
//

#ifndef PLATFORMER_PHYSICSSERVICEWRAPPER_H
#define PLATFORMER_PHYSICSSERVICEWRAPPER_H

class PhysicsServiceWrapper {

};

#endif //PLATFORMER_PHYSICSSERVICEWRAPPER_H
